query allCrates($search: String, $orderBy: LootOrderBy) {
  allCrates (orderBy: name_ASC) {
    id
    name
    description
    file {
      id
      url
    }
    loots (filter: { OR: [{ dataId_contains: $search }, { name_contains: $search }, {amount_contains: $search }] }, orderBy: $orderBy) {
      dataId
      id
      name
      percentage
      amount
      blueprint
      category (filter: { OR: [{ name_contains: $search }] }) {
        id
        name
      }
    }
    lootCount: _lootsMeta {
      count
    }
  }
}
